#spring.profiles.active: local # default profile
#management.endpoints.web.exposure.include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pholedge?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  flyway:
    baselineOnMigrate: true

mybatis:
  mapperLocations: classpath*:com/**/mapper/*.xml